name: Lambda Application CI workflow

on:
  push:
    branches:
      - main

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: read-python-version
        run: printf "version=$(cat .python-version)\n" >> "$GITHUB_OUTPUT"

      - uses: actions/setup-python@v5
        with:
          python-version: "${{ steps.read-python-version.outputs.version }}"

      - name: Restore python virtual environment
        uses: actions/cache/restore@v4
        with:
          path: .venv
          key: ${{ hashFiles('poetry.lock') }}

      - name: Install project dependencies
        run: |
          poetry install --no-root
