name: Lambda Application CI workflow

on:
  push:
    branches:
      - main

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read Python version
        id: read-python-version
        run: printf "version=$(cat .python-version)\n" >> "$GITHUB_OUTPUT"

      - name: Install Python
        id: install-python
        uses: actions/setup-python@v5
        with:
          python-version: "${{ steps.read-python-version.outputs.version }}"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-in-project: true

      - name: Restore Python virtual environment
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.install-python.outputs.python-version }}-${{ hashFiles('poetry.lock') }}

      - name: Install project dependencies
        run: |
          poetry install --no-interaction --no-root
          poetry self add poetry-plugin-export
          poetry export --without-hashes --without dev -f requirements.txt > requirements.txt

      - name: Run tests
        run: |
          poetry run pytest
