name: Lambda Application CI workflow

on:
  push:
    branches:
      - main

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: read Python version
        id: read-python-version
        run: echo "version=${cat .python-version}\n" >> "$GITHUB_OUTPUT"

      - uses: actions/setup-python@v5
        with:
          python-version: "${{ steps.read-python-version.outputs.version }}"
